### PR TITLE
add: card component

### PR DESCRIPTION
**Pull request by ApurvaSawant11**
Added Card Component. Please review the PR.

### CODE REVIEW

**Review by nayyyhaa — APPROVED** [review]
Nice work! Love that badge on the card component! 💯

**Comment by ApurvaSawant11** [comment]
> Nice work! Love that badge on the card component! 💯
Thank you so much!

**Review by b0llu — APPROVED** [review]
Clean code. Nice work!

**Comment by aayushjain-code** [comment]
Nice work it looks clean and elegant!!

**Pull request merged**
